# operator=input("Enter the operator (+,/,*,-): ")
# num1=float(input("Enter the first no.: "))
# num2=float(input("Enter the second no.: "))
# if(operator == "+"):
#     print(round(num1+num2, 3))
# elif(operator == "-"):
#     print(round(num1-num2, 3))
# elif(operator == "*"):
#     print(round(num1*num2))
# elif(operator == "/"):
#     print(round(num1/num2))
# else:
#     print("Invalid operator")

width=int(input("enter the width"))
length=int(input("enter the length"))
area=length*width
print(area)